### PR TITLE
Avoid multiple api loads

### LINKED ISSUE #954: google-map-react now load google maps api all the time even if a key  is not provided
**Describe the bug 🐛**

I use this lib, but I manually load the google maps api.
now i just found out that the lib is loaded multiple time:

> You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

Using latest version

### PR DESCRIPTION
**Pull request by itsmichaeldiego**
Fix #954

Introduced in #942 and dragged to #946

### CODE REVIEW

File: src/loaders/google_map_loader.js [hunk 1]
```diff
@@ -50,23 +54,21 @@ export default (bootstrapURLKeys, heatmapLibrary) => {
     throw new Error('google map cannot be loaded outside browser env');
   }
 
-  if (!loader_) {
```
Comment (itsmichaeldiego) [inline src/loaders/google_map_loader.js:53]: @jpoehnelt I feel there's no need to check for this, that doesn't change much, because loader will load another script anyways.

File: src/loaders/google_map_loader.js [hunk 2]
```diff
@@ -16,6 +15,11 @@ export default (bootstrapURLKeys, heatmapLibrary) => {
     return _customPromise;
   }
 
+  // avoid api to be loaded multiple times
+  if (loadPromise_) {
```
Comment (itsmichaeldiego) [inline src/loaders/google_map_loader.js:19]: @jpoehnelt Instead of checking for `!loader_` we return the promise, avoiding the loader to add another script
